name: build-x86-64-openwrt-24.10.1

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'RootFS 分割區大小(MB)'
        default: '2048'
        required: true
      include_docker:
        description: '是否編譯 Docker 套件'
        default: 'yes'
        type: choice
        options: [ 'yes', 'no' ]
      set_brlan_ipv4:
        description: '是否自訂 br-lan IPv4'
        default: 'yes'
        type: choice
        options: [ 'yes', 'no' ]
      brlan_ipv4:
        description: 'br-lan IPv4 (留空採預設 192.168.2.1)'
        required: false
      enable_modem_manager:
        description: '是否啟用 ModemManager 設定'
        type: choice
        required: true
        default: 'yes'
        options: [ 'yes', 'no' ]
      modem_manager_apn:
        description: 'APN（啟用時必填)'
        default: 'internet'
        required: false
      modem_manager_pin:
        description: 'SIM PIN'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set executable permissions
        run: chmod +x ${{ github.workspace }}/x86-64/make_openwrt_image.sh

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3 qemu-utils genisoimage zstd

      - name: Validate ModemManager inputs
        run: |
          if [[ "${{ inputs.enable_modem_manager }}" == "yes" ]]; then
            if [[ -z "${{ inputs.modem_manager_apn }}" ]]; then
              echo "Error: modem_manager_apn must be provided when ModemManager is enabled!"
              exit 1
            fi
          fi

      - name: Build openwrt-x86-64-efi
        run: |
          profiles="${{ github.event.inputs.profile }}"
          include_docker="${{ github.event.inputs.include_docker }}"
          IFS=',' read -r -a profile_array <<< "$profiles"

          for profile in "${profile_array[@]}"; do
            echo "Building for profile: $profile"

            docker run --rm -i \
              --user root \
              -v "${{ github.workspace }}/bin:/builder/bin:rw \
              -v "${{ github.workspace }}/config.sed:/builder/config.sed \
              -v "${{ github.workspace }}/files:/builder/files" \
              -v "${{ github.workspace }}/x86-64/24.10/make_openwrt_image.sh:/builder/make_openwrt_image.sh" \
              -e PROFILE=$profile \
              -e INCLUDE_DOCKER=$include_docker \
              -e SET_BRLAN_IPV4=${{ inputs.set_brlan_ipv4 }} \
              -e BRLAN_IPV4=${{ inputs.brlan_ipv4 }} \
              -e ENABLE_MODEM_MANAGER=${{ inputs.enable_modem_manager }} \
              -e MODEM_MANAGER_APN="${{ inputs.modem_manager_apn }}" \
              -e MODEM_MANAGER_PIN="${{ inputs.modem_manager_pin }}" \
              openwrt/imagebuilder:x86-64-openwrt-24.10 \
              /bin/bash /builder/make_openwrt_image.sh
          done

      - name: Create info
        run: |
          if [ "${{ github.event.inputs.include_docker }}" == "yes" ]; then
            extra_content="#### With Docker"
            echo -e "\n $extra_content" >> ${{ github.workspace }}/info.md
          else
            echo -e "NO docker"
          fi

      - name: Upload openwrt as release assets
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: Autobuild-x86-64
          body_path: ${{ github.workspace }}/info.md
          files: |
            ${{ github.workspace }}/*squashfs-combined-efi.img.gz
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}