# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  build:
  
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      
      - uses: actions/checkout@v3

      - uses: robinraju/release-downloader@v1.8
        with:
          repository: "izer-xyz/librespot-openwrt"
          latest: true
          fileName: "*.ipk"
          out-file-path: "packages"
       
      - uses: izer-xyz/openwrt-imagebuilder-action@main
        with:
          image: x86-64
          profile: generic
          openwrt-version: 24.10.1
          packages: >-
            -luci-i18n-dockerman-zh-tw -modemmanager -luci-proto-modemmanager -curl 
            -luci-i18n-firewall-zh-tw -luci-i18n-package-manager-zh-tw 
            -luci-i18n-ttyd-zh-tw -script-utils -base-files -ca-bundle -dnsmasq -dropbear 
            -e2fsprogs -firewall4 -fstools -grub2-bios-setup -kmod-button-hotplug -kmod-nft-offload 
            -libc -libgcc -libustream-mbedtls -logd -mkf2fs -mtd -netifd -nftables 
            -odhcp6c -odhcpd-ipv6only -opkg -partx-utils -procd-ujail -uci -uclient-fetch 
            -urandom-seed -urngd -kmod-amazon-ena -kmod-amd-xgbe -kmod-bnx2 -kmod-dwmac-intel 
            -kmod-e1000e -kmod-e1000 -kmod-forcedeth -kmod-fs-vfat -kmod-igb -kmod-igc -kmod-ixgbe 
            -kmod-r8169 -kmod-tg3 -luci -kmod-mtk-t7xx -kmod-phy-aquantia -kmod-sfp -kmod-wwan 
            -kmod-usb-net-rndis -kmod-usb-serial -kmod-usb-serial-option -kmod-usb3 -luci-proto-mbim 
            -luci-proto-ncm -comgt -pciutils -usbutils -block-mount -ethtool-full 
            -iperf3 -luci-i18n-base-zh-tw -kmod-usb-net-cdc-mbim -umbim -picocom 
            -kmod-scsi-core -kmod-block2mtd -fdisk -lsblk -speedtest-go -kmod-tcp-bbr 
            -luci-i18n-uhttpd-zh-tw -luci-i18n-sqm-zh-tw -luci-i18n-cloudflared-zh-tw -luci-i18n-acme-zh-tw 
            -luci-app-uhttpd -luci-app-sqm -luci-app-acme -kmod-usb-serial-wwan
          files: test/files
          rootfs-size: 10
          #debug: 1
          #disabled-services: dhcp
         # extra-image-name: useless

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: x86-64
          path: bin/*
          
      - run: |
          sudo chmod -R a+rw ./bin
          ls -la ./bin
          gzip -d --force ./bin/generic-squashfs-combined-efi.img.gz || true
          docker run --rm \
            -v $(pwd)/bin:/openwrt \
            tianon/qemu \
              qemu-system-x86_64 \
                -machine q35,accel=tcg \
                -m 1024M -smp 2 \
                -nographic \
                -nic user,model=e1000 \
                -drive file=/openwrt/generic-squashfs-combined-efi.img,format=raw
                -nic user,model=e1000 \
                -drive file=/openwrt/generic-squashfs-combined-efi.img,if=virtio,format=raw \
                -append "root=/dev/vda2"
